<hr />
<h3><strong>Call Back RINGY &#8211; what is it?</strong></h3>
<p style="text-align: justify;"><strong>Thanks to our callback widget RINGY</strong>, we will help you <strong>increase conversion</strong> through <strong>the increase of  phone calls</strong> and finally, the <strong>sales volume</strong>.</p>
<p><strong>The widget contains a button</strong> that is placed prominently on your website. After requesting a callback through the widget, <strong>a call is established between the number provided by the Customer</strong> and an employee from the selected department in your company.</p>
<p><a href="https://www.telecube.pl/wp-content/uploads/2018/06/ringy_callback_telecube.jpg"><img class="alignnone wp-image-2994 size-full" src="https://www.telecube.pl/wp-content/uploads/2018/06/ringy_callback_telecube.jpg" alt="Call back RINGY w telefonii TeleCube" width="650" height="304" srcset="https://www.telecube.pl/wp-content/uploads/2018/06/ringy_callback_telecube.jpg 650w, https://www.telecube.pl/wp-content/uploads/2018/06/ringy_callback_telecube-300x140.jpg 300w" sizes="(max-width: 650px) 100vw, 650px" /></a></p>
<p>After clicking the button, the Customer enters his/her phone number in the newly opened window (popup) and in a moment the connection is dialed with this number and connected with your company (alternatively the Customer may also choose the option of connecting at later, determined by him date).</p>
<p>You can also give the Customer a choice of specific departments within your company or types of cases, so that you he/she is connected with consultants best suited to help your client</p>
<p><a href="https://www.telecube.pl/wp-content/uploads/2018/05/popup_callback_ringy.jpg"><img class="alignnone size-full wp-image-2920" src="https://www.telecube.pl/wp-content/uploads/2018/05/popup_callback_ringy.jpg" alt="Popup callback ringy" width="650" height="317" srcset="https://www.telecube.pl/wp-content/uploads/2018/05/popup_callback_ringy.jpg 650w, https://www.telecube.pl/wp-content/uploads/2018/05/popup_callback_ringy-300x146.jpg 300w" sizes="(max-width: 650px) 100vw, 650px" /></a></p>
<p>It is a very convenient solution for people visiting your website because <strong>they can connect to you for free and quickly find out more about your products and services.</strong></p>
<p>Connection costs are borne by your company in accordance with <a href="https://www.telecube.pl/cennik-polaczen-i-pakietow/">our pricelist</a>.</p>
<p><strong>The price for RINGY until August 31, 2018</strong>, is <strong>19 PLN + VAT / month / per domain</strong>. If you have, for example, three pages and you would like to use RINGY on each of them, you will pay three times the monthly fee.</p>
<p><strong>Please Note!</strong> If you would like to buy RINGY later, we would like to inform you that<strong> from September 1, 2018, its price will increase and will amount to 29 PLN + VAT / month / per domain.</strong></p>
<p>Do not wait - <strong>activate RINGY today</strong>! We also offer a free trial period!</p>
<p>To be able to use RINGY, you must have any of <a href="https://www.telecube.pl/wirtualna-centrala-telefoniczna/">TeleCube PBX plan</a> (available from 29 PLN + VAT / month) or <a href="https://www.telecube.pl/voip/" target="_blank" rel="noopener">Mini VoIP plan</a> (for 9 PLN + VAT / month).</p>