<hr />
<h3><strong>Call Back RINGY &#8211; co to jest?</strong></h3>
<p style="text-align: justify;"><strong>Dzięki</strong> zastosowaniu na swojej stronie www, widgetu <strong>callback RINGY</strong>, zdecydowanie <strong>zwiększysz</strong> jej <strong>konwersję</strong>, <strong>ilość zrealizowanych rozmów</strong> telefonicznych, a finalnie <strong>wolumen sprzedaży</strong>.</p>
<p><strong>Widget zawiera przycisk</strong>, który jest umieszczony w widocznym miejscu na stronie www. Przez to łatwo go zauważyć i kliknąć w niego. Takie zachowanie Klienta powoduje, że w ciągu kilku sekund, <strong>następuje oddzwonienie na numer podany przez tego Klienta</strong> (numer należy wyszczególnić w formularzu, o którym piszemy poniżej), a konkretnie zestawienie połączenia pomiędzy Klientem, a konsultantem/pracownikiem z wybranego działu Twojej firmy.</p>
<p><a href="https://www.telecube.pl/wp-content/uploads/2018/06/ringy_callback_telecube.jpg"><img class="alignnone wp-image-2994 size-full" src="https://www.telecube.pl/wp-content/uploads/2018/06/ringy_callback_telecube.jpg" alt="Call back RINGY w telefonii TeleCube" width="650" height="304" srcset="https://www.telecube.pl/wp-content/uploads/2018/06/ringy_callback_telecube.jpg 650w, https://www.telecube.pl/wp-content/uploads/2018/06/ringy_callback_telecube-300x140.jpg 300w" sizes="(max-width: 650px) 100vw, 650px" /></a></p>
<p>Po kliknięciu w przycisk, Klient wpisuje w nowootwartym okienku (popupie) swój numer telefonu i za moment z tym numerem oraz numerem Twojej firmy jest zestawiane połączenie (ewentualnie Klient może też wybrać opcję połączenia w późniejszym, określonym przez niego terminie).</p>
<p>Jeśli chcesz możesz dać Klientowi również do wyboru, konkretne działy Twojej firmy, czy też rodzaje spraw, tak żeby od razu skierować go (połączenie) do odpowiedniego adresata.</p>
<p><a href="https://www.telecube.pl/wp-content/uploads/2018/05/popup_callback_ringy.jpg"><img class="alignnone size-full wp-image-2920" src="https://www.telecube.pl/wp-content/uploads/2018/05/popup_callback_ringy.jpg" alt="Popup callback ringy" width="650" height="317" srcset="https://www.telecube.pl/wp-content/uploads/2018/05/popup_callback_ringy.jpg 650w, https://www.telecube.pl/wp-content/uploads/2018/05/popup_callback_ringy-300x146.jpg 300w" sizes="(max-width: 650px) 100vw, 650px" /></a></p>
<p>Jest to rozwiązanie bardzo wygodne dla osób odwiedzających Twoją stronę www, ponieważ <strong>bezpłatnie i do tego w bardzo szybkim czasie mogą się z Tobą połączyć i uzyskać konkretne informacje</strong> np. o Twoim produkcie.</p>
<p>Koszty połączenia ponosi Twoja firma, a stawka za połączenie jest zgodna z <a href="https://www.telecube.pl/cennik-polaczen-i-pakietow/">cennikiem TeleCube</a>.</p>
<p><strong>Cena za RINGY do 31 sierpnia 2018 roku</strong>, wynosi <strong>19 zł netto / miesiąc</strong> i dotyczy umiejscowienia go <strong>na jednej stronie www</strong>. Jeśli masz np. 3 strony i chcesz na każdej z nich korzystać z RINGY, zapłacisz za niego: 57 zł netto / miesiąc.</p>
<p><strong>Ważne!</strong> Jeśli będziesz chciał zakupić RINGY póżniej, informujemy, że<strong> od 1 września br. jego cena wzrośnie i wyniesie 29 zł netto / miesiąc / 1 widget.</strong></p>
<p>Nie czekaj zatem, i <strong>kup RINGY już teraz</strong>! Jeśli się wahasz, <strong>polecamy najpierw skorzystanie z okresu testowego RINGY</strong> (o czym piszemy, w dalszej części niniejszej notatki). </p>
<p>Aby móc korzystać z RINGY musisz mieć wykupiony w TeleCube dowolny <a href="https://www.telecube.pl/wirtualna-centrala-telefoniczna/">pakiet wirtualnej centrali</a> (dostępny od 29 zł netto / miesiąc) lub pakiet <a href="https://www.telecube.pl/voip/" target="_blank" rel="noopener">Mini VoIP</a> (kosztuje 9 zł netto / miesiąc).</p>